export const CHANGE_REQUEST = 'CHANGE_REQUEST';
export const ADD_VERSION = 'ADD_VERSION';
export const ADD_VERSION_FAILED = 'ADD_VERSION_FAILED';
export const SWAP_VERSION = 'SWAP_VERSION';

export const RESET_STATE = 'RESET_STATE';
export const RESET_STATE_FAILED = 'RESET_STATE_FAILED';
export const SWAP_STATE = 'SWAP_STATE';
export const SWAP_STATE_FAILED = 'SWAP_STATE_FAILED';
export const EVENT_HANDLED = 'EVENT_HANDLED';
export const EVENT_FAILED = 'EVENT_FAILED';
export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';

export const STRING_LIT_CURSOR = 'STRING_LIT_CURSOR';
export const STRING_LIT_INSERT = 'STRING_LIT_INSERT';
